#!/bin/bash
#SBATCH --job-name=rois
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --mem=4G
#SBATCH --nodes=1
#SBATCH --time=1-0:00:00
#SBATCH -o rois.log
#SBATCH --constraint="intel"

find /tmp -maxdepth 1 -type d -user pssadil -exec rm -r {} \;

source ~/.bashrc

mamba activate meta
ml matlab
ml fsl
export PATH=/dcl01/smart/data/psadil/meta/tools:/users/pssadil/workbench/bin_rh_linux64:${PATH}:/users/pssadil/git/PALM

#Rscript -e "targets::tar_make(c(glm_pop_ukb))"
Rscript -e "targets::tar_make(c(rois_all))"
#Rscript -e "targets::tar_make(study_to_gold_distances)"
