#!/bin/bash
#SBATCH -J act_preds
#SBATCH --array=0-1
#SBATCH --output act-preds_%a.log
#SBATCH -t 24:00:00
#SBATCH --mem=1G
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1

source ~/.bashrc

mamba activate act_preds2

python entrypoint.py $PWD cpm-difumo.parquet hcp.parquet --measure "${SLURM_ARRAY_TASK_ID}" 

