#!/bin/bash
#SBATCH -J act_preds
#SBATCH --output logs/act-preds_%a.log
#SBATCH -t 24:00:00
#SBATCH --mem=4G
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --constraint="intel"

source ~/.bashrc

mamba activate act_preds2

mapfile -t array <<<"$(cat hcp-iters.tsv)"
line="${array[${SLURM_ARRAY_TASK_ID}]}"
task=$(echo "${line}" | cut -f 1)
type=$(echo "${line}" | cut -f 2)
measure=$(echo "${line}" | cut -f 3)
confounds=$(echo "${line}" | cut -f 4)

python entrypoint.py $PWD cpm-schaefer.parquet "${confounds}" "${measure}" "${type}" "${task}"
