#!/bin/bash

    SmoothingList="2" #Space delimited list for setting different final smoothings.  2mm is no more smoothing (above minimal preprocessing pipelines grayordinates smoothing).  Smoothing is added onto minimal preprocessing smoothing to reach desired amount
    LowResMesh="32" #32 if using HCP minimal preprocessing pipeline outputs
    GrayOrdinatesResolution="2" #2mm if using HCP minimal preprocessing pipeline outputs
    OriginalSmoothingFWHM="2" #2mm if using HCP minimal preprocessing pipeline outputes
    Confound="NONE" #File located in ${SubjectID}/MNINonLinear/Results/${fMRIName} or NONE
    HighpassFilter="200" #Use 2000 for linear detrend, 200 is default for HCP task fMRI, NONE to turn off
    VolumeBasedProcessing="YES" #YES or NO. CAUTION: Only use YES if you want unconstrained volumetric blurring of your data, otherwise set to NO for faster, less biased, and more senstive processing (grayordinates results do not use unconstrained volumetric blurring and are always produced).  
    RegNames="NONE" # Use NONE to use the default surface registration
    ProcSTRING="NONE" #Any preprocesing beyond CIFTI mapping and surface registration, e.g. spatial and temporal ICA cleanup or NONE
    ParcellationList="NONE" # Use NONE to perform dense analysis, non-greyordinates parcellations are not supported because they are not valid for cerebral cortex.  Parcellation superseeds smoothing (i.e. smoothing is done)
    ParcellationFileList="NONE" # Absolute path the parcellation dlabel file.  Also accepts NONE when the ptseries already exists and does not need to be generated.



"$HCPPIPEDIR"/TaskfMRIAnalysis/TaskfMRIAnalysis.sh \
                            --study-folder="$StudyFolder" \
                            --subject="$Subject" \
                            --lvl1tasks="$LevelOneTasks" \
                            --lvl1fsfs="$LevelOneFSFs" \
                            --lvl2task="$LevelTwoTask" \
                            --lvl2fsf="$LevelTwoFSF" \
                            --lowresmesh="$LowResMesh" \
                            --grayordinatesres="$GrayOrdinatesResolution" \
                            --origsmoothingFWHM="$OriginalSmoothingFWHM" \
                            --confound="$Confound" \
                            --finalsmoothingFWHM="$FinalSmoothingFWHM" \
                            --highpassfilter="$HighpassFilter" \
                            --vba="$VolumeBasedProcessing" 