#!/bin/bash
#SBATCH --job-name=palm_pop
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --time=1-00:00:00
#SBATCH -o data-raw/logs/palm_pop_%a
#SBATCH --constraint="intel&(haswell|cascadelake)"
#SBATCH --array=2-14

ml matlab
ml fsl
export PATH=/dcl01/smart/data/psadil/meta/tools:/users/pssadil/workbench/bin_rh_linux64:${PATH}:/users/pssadil/git/PALM

cmd=$( cat tools/tfce_pop_inputs | sed "${SLURM_ARRAY_TASK_ID}q;d" )

eval "${cmd}"

