#!/bin/bash
#SBATCH --job-name=palm20_vol
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --time=3-00:00:00
#SBATCH -o data-raw/logs/palm_20_vol_%a
#SBATCH --constraint="intel&(haswell|cascadelake)"
#SBATCH --array=1-700

ml matlab
ml fsl
export PATH=/dcl01/smart/data/psadil/meta/tools:/users/pssadil/workbench/bin_rh_linux64:${PATH}:/users/pssadil/git/PALM

cmd=$( cat tools/palm_cmds_20_vol | sed "${SLURM_ARRAY_TASK_ID}q;d" )

eval "${cmd}"

