#!/bin/bash
#SBATCH --job-name=rois
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=16G
#SBATCH --nodes=1
#SBATCH --time=4-0:00:00
#SBATCH -o rois.log
#SBATCH --constraint="intel"

find /tmp -maxdepth 1 -type d -user pssadil -exec rm -r {} \;

source ~/.bashrc

mamba activate meta
ml matlab
ml fsl
export PATH=/dcl01/smart/data/psadil/meta/tools:/users/pssadil/workbench/bin_rh_linux64:${PATH}:/users/pssadil/git/PALM
export FSLOUTPUTTYPE=NIFTI_GZ

Rscript -e "targets::tar_make()"
