#!/bin/bash

#$ -l mem_free=3G 
#$ -l h_vmem=3G
#$ -pe local 2 
#$ -cwd

module load R/4.0.3

Rscript -e "install.packages('remotes')"
Rscript -e "remotes::install_github('rstudio/renv@0.14.0')"
Rscript -e 'renv::restore()'

