#!/bin/bash

#$ -l mem_free=2G 
#$ -l h_vmem=2G
#$ -cwd
#$ -m e
#$ -M psadil1@jh.edu

module load R/4.0.3

STORE='${MYSCRATCH}/_ale'

Rscript -e "targets::tar_make_future(script='_ale.R', workers = 100, store=${STORE})"

mv "${MYSCRATCH}"/_ale ./_ale

