#!/bin/bash

#Rscript -e "targets::tar_make_clustermq(script='_tfce.R', workers = 35, store='_tfce')"
Rscript -e "targets::tar_make_future(script='_tfce1.R', workers = 10, store='_tfce1')"
#Rscript -e "targets::tar_make(script='_tfce1.R', store='_tfce1')"

