#!/bin/bash

#$ -l mem_free=2G 
#$ -l h_vmem=2G
#$ -cwd

# module load conda_R/4.1.x
conda activate meta_R

Rscript -e "targets::tar_make_future(script='_ale.R', workers = 100, store='/fastscratch/myscratch/pssadil/_targets')"

