#!/bin/bash
#SBATCH --job-name=ukb_pop
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G
#SBATCH -o data-raw/ukb_pop.log
#SBATCH --time=6:00:00

set -xeu

# echo "merging"
# fslmerge -t data-raw/ukb_mni_all.nii.gz data-raw/ukb_mni/*gz
# gunzip -k data-raw/ukb_mni_all.nii.gz

echo "average"
niimath data-raw/ukb_mni_all.nii -Tmean data-raw/ukb_mni_all_tmean.nii.gz 
echo "standard dev"
niimath data-raw/ukb_mni_all.nii -Tstd data-raw/ukb_mni_all_tstd.nii.gz 

niimath data-raw/ukb_mni_all_tmean.nii.gz \
    -div data-raw/ukb_mni_all_tstd.nii.gz \
    data-raw/glm_manual/nsub-38347_iter-0_task-EMOTION_cope-5_type-UKB_tstat1.nii.gz
