#!/bin/bash

set -ue

cmd="git annex addurl --raw --pathdepth=-1"
baseurl="file:///home/ubuntu/mnt/fmri"
# baseurl="file:///home/psadil/Documents/git/raw"

for line in $(cat .ukbbatch |  sed 's/ /,/g'); do
    sub_id=${line%,*}
    modality=${line#*,}

    case "${modality}" in
      20227_2_0 | 20252_2_0 | 20249_2_0)
        $cmd -c annex.security.allowed-url-schemes="http https ftp file" "$baseurl/${sub_id}_${modality}.zip"
        ;;
      25750_2_0 | 25751_2_0 | 25752_2_0 | 25753_2_0)
        $cmd -c annex.security.allowed-url-schemes="http https ftp file" "$baseurl/${sub_id}_${modality}.txt"
        ;;
      *)
        error "Unexpected modality '${modality}'"
        ;;
    esac
done
