#!/bin/bash
#SBATCH --job-name=warp
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=3G
#SBATCH -o data-raw/warp-log/ukbwarp_%a.log
#SBATCH --array 0-1
#SBATCH --time=1:00:00

ROOT=/dcl01/smart/data/psadil/meta
UKB_ROOT=/dcs07/smart/data/ukb/rawdata
COPES_RAW=${ROOT}/data-raw/ukb_copes_raw
UKB_SUBS=${ROOT}/data-raw/ukb_subs
find $UKB_ROOT -mindepth 1 -maxdepth 1 -type d > ${UKB_SUBS}
readarray -t subs < ${UKB_SUBS}
copes=()
for sub in "${subs[@]}"; do
    cope5="${sub}"/ses-2/non-bids/20249/fMRI/tfMRI.feat/stats/cope5.nii.gz
    if [[ -f $cope5 ]]; then
        copes+=( "${cope5}" )
    fi
done
printf "%s\n" "${copes[@]}" > ${COPES_RAW}


batch=0
n_max_array=10000
module load fsl


set -eu

warp() { 
    local infile="$1"
    local sub
    sub=$(echo "${infile}" | grep -oP "[0-9]{7}")
    out=/data-raw/ukb_mni/sub-"${sub}"_task-EMOTION_space-MNI152_contrast-5_cope.nii.gz 
    local statsdir
    statsdir=$(dirname "${infile}")
    local featdir
    featdir=$(dirname "${statsdir}")
    local warp="${featdir}"/reg/example_func2standard_warp


    if [[ -f $out || ! -f $infile ]]; then
        return
    fi    

    echo "working on ${sub}"
    echo "${infile}"
    echo "${out}"

    applywarp \
        -r "${FSLDIR}"/data/standard/MNI152_T1_2mm \
        -i "${infile}" \
        -w "${warp}" \
        -o "${out}"

}
export -f warp

readarray -t copes < ${COPES_RAW}
i=$(( SLURM_ARRAY_TASK_ID + n_max_array*batch ))
warp "${copes[$i]}"
